services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-5000}:${CLIENT_PORT:-5000}"
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client:/app
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=${CLIENT_PORT:-5000}
      - SERVER_URL=http://server:4000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"
    volumes:
      - ./server:/app
    env_file:
      - .env
    environment:
      - FLASK_RUN_PORT=${SERVER_PORT:-4000}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP:-server.py}
      - FIREBASE_BUCKET=${FIREBASE_BUCKET}
