services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-8501}:8501"
    depends_on:
      - server
    volumes:
      - ./client:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - SERVER_URL=${SERVER_URL}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    volumes:
      - ./server:/app
    env_file:
      - .env
    environment:
      - FLASK_RUN_PORT=4000
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP:-server.py}
      - FIREBASE_BUCKET=${FIREBASE_BUCKET}
