services:
  client:
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client/src:/streamlit-app/src
    environment:
      - PORT=5000
      - ENV FLASK_ENV=development
      - ENV FLASK_APP=app.py

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server-app
    env_file:
      - .env
    # environment:

